--- 
- 
  become: true
  hosts: appserver
  task: 
    - 
      apt: 
        update_cache: true
      name: "update packages"
    - 
      apt: 
        name: tomcat7
        state: present
      name: "install tomcat"
